# .github/workflows/performance-tests.yml
name: Performance Tests

on:
  schedule:
   # - cron: '0 1 * * *'  # every day at 01:00 UTC

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Locust
      run: |
        pip install locust

    - name: Run Locust performance tests
      run: |
        mkdir -p reports
        locust -f performance/locustfile.py --headless -u 10 -r 2 -t1m --host=https://example.com --csv=reports/locust

    - name: Push Locust Results to InfluxDB
      env:
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
        INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      run: |
        python utils/push_metrics.py --type performance --input reports/locust_stats.csv
