# .github/workflows/python-tests.yml
name: Functional Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest --maxfail=1 --disable-warnings --tb=short --json-report --json-report-file=reports/pytest_report.json

    - name: Push Pytest Results to InfluxDB
      env:
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
        INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      run: |
        python utils/push_metrics.py --type functional --input reports/pytest_report.json