# .github/workflows/security-tests.yml
name: Security Tests

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run ZAP stub scan
      run: |
        mkdir -p reports
        python security/zap_stub.py > reports/zap_output.log

    - name: Push ZAP Scan Metrics to InfluxDB
      env:
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
        INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      run: |
        python utils/push_metrics.py --type security --input reports/zap_output.log